[colors]
background = '#0f0e06'
foreground = '#cfbcba'
selection-background = '#3f1324'
selection-foreground = '#cfbcba'
cursor = '#ffaa33'
black = '#26211d'
red = '#ef656a'
green = '#2fa526'
yellow = '#c48702'
blue = '#379cf6'
magenta = '#d570af'
cyan = '#4fb0cf'
white = '#cfbcba'
dim-black = '#26211d'
dim-red = '#df7f7f'
dim-green = '#5f9f6f'
dim-yellow = '#cf9f7f'
dim-blue = '#6a84af'
dim-magenta = '#c590af'
dim-cyan = '#82a0af'
dim-white = '#887c8a'
light-black = '#56524f'
light-red = '#ff7a7f'
light-green = '#00b066'
light-yellow = '#df8f6f'
light-blue = '#029fff'
light-magenta = '#af8aff'
light-cyan = '#3dbbb0'
light-white = '#887c8a'
