[colors]
background = '#ffead8'
foreground = '#393330'
selection-background = '#dbe0c0'
selection-foreground = '#393330'
cursor = '#208f10'
black = '#f0d8cf'
red = '#b0000f'
green = '#007000'
yellow = '#906200'
blue = '#375cc6'
magenta = '#a23ea4'
cyan = '#3f69af'
white = '#393330'
dim-black = '#f0d8cf'
dim-red = '#8f2f30'
dim-green = '#3f712f'
dim-yellow = '#8d6068'
dim-blue = '#4a659f'
dim-magenta = '#845592'
dim-cyan = '#546f70'
dim-white = '#6e678f'
light-black = '#c7b2ab'
light-red = '#aa184f'
light-green = '#00704f'
light-yellow = '#8a6340'
light-blue = '#265fbf'
light-magenta = '#6448ca'
light-cyan = '#0f7688'
light-white = '#6e678f'
