[colors]
background = '#111111'
foreground = '#cfdfd5'
selection-background = '#3a3027'
selection-foreground = '#cfdfd5'
cursor = '#35f038'
black = '#222522'
red = '#ef6560'
green = '#3fb83f'
yellow = '#d4aa02'
blue = '#37aff6'
magenta = '#d38faf'
cyan = '#6fc5ef'
white = '#cfdfd5'
dim-black = '#222522'
dim-red = '#d56f72'
dim-green = '#7fc07f'
dim-yellow = '#b7a07f'
dim-blue = '#6ab4cf'
dim-magenta = '#caa5bf'
dim-cyan = '#7fb4cf'
dim-white = '#808f80'
light-black = '#505250'
light-red = '#ff778f'
light-green = '#00c089'
light-yellow = '#cfc04f'
light-blue = '#32cfef'
light-magenta = '#af9fff'
light-cyan = '#5dc0aa'
light-white = '#808f80'
