[colors]
background = '#fcf7ef'
foreground = '#242521'
selection-background = '#e0e7e5'
selection-foreground = '#242521'
cursor = '#007f00'
black = '#f0ece0'
red = '#9f0d0f'
green = '#006f00'
yellow = '#a7601f'
blue = '#375cc6'
magenta = '#9a456f'
cyan = '#1f70af'
white = '#242521'
dim-black = '#f0ece0'
dim-red = '#b05350'
dim-green = '#3a6f48'
dim-yellow = '#8f6f4a'
dim-blue = '#4a659f'
dim-magenta = '#804f60'
dim-cyan = '#4f677f'
dim-white = '#59786f'
light-black = '#c5c3b8'
light-red = '#ca3400'
light-green = '#00824f'
light-yellow = '#a2604f'
light-blue = '#065fbf'
light-magenta = '#8448aa'
light-cyan = '#007a9f'
light-white = '#59786f'
