[colors]
background = '#190a0f'
foreground = '#d3cfcf'
selection-background = '#232f3f'
selection-foreground = '#d3cfcf'
cursor = '#ff5aaf'
black = '#291f26'
red = '#ff7359'
green = '#60b444'
yellow = '#e5b76f'
blue = '#8fa5f6'
magenta = '#ef80bf'
cyan = '#8fbaef'
white = '#d3cfcf'
dim-black = '#291f26'
dim-red = '#e47f72'
dim-green = '#61a06c'
dim-yellow = '#bf9f8f'
dim-blue = '#7f9ab4'
dim-magenta = '#cc9bcf'
dim-cyan = '#aac0cf'
dim-white = '#808898'
light-black = '#594a4f'
light-red = '#ff78aa'
light-green = '#60bf88'
light-yellow = '#f59280'
light-blue = '#7fa5ff'
light-magenta = '#df7fff'
light-cyan = '#8fcfdf'
light-white = '#808898'
