[colors]
background = '#fff5ea'
foreground = '#584141'
selection-background = '#f0d2df'
selection-foreground = '#584141'
cursor = '#cf1f00'
black = '#f2e9db'
red = '#ba2d2f'
green = '#007a0a'
yellow = '#a45a22'
blue = '#375cc6'
magenta = '#ca3e54'
cyan = '#3f60af'
white = '#584141'
dim-black = '#f2e9db'
dim-red = '#b05350'
dim-green = '#61756c'
dim-yellow = '#9a625a'
dim-blue = '#4a659f'
dim-magenta = '#a04450'
dim-cyan = '#4f6f8f'
dim-white = '#63728f'
light-black = '#c9c0b8'
light-red = '#cf2f4f'
light-green = '#0f7f5f'
light-yellow = '#aa4f30'
light-blue = '#265fbf'
light-magenta = '#8448aa'
light-cyan = '#0f7b8f'
light-white = '#63728f'
