[colors]
background = '#000000'
foreground = '#d0d0d0'
selection-background = '#2a234a'
selection-foreground = '#d0d0d0'
cursor = '#ff76ff'
black = '#1a1a1a'
red = '#ef6560'
green = '#0faa26'
yellow = '#bf9032'
blue = '#3f95f6'
magenta = '#d369af'
cyan = '#4fbaef'
white = '#d0d0d0'
dim-black = '#1a1a1a'
dim-red = '#d56f72'
dim-green = '#61a06c'
dim-yellow = '#cf9f8f'
dim-blue = '#7a94df'
dim-magenta = '#c58faf'
dim-cyan = '#8aa0df'
dim-white = '#857f8f'
light-black = '#4b4b4b'
light-red = '#ff5a7a'
light-green = '#00a692'
light-yellow = '#df8a5a'
light-blue = '#029fff'
light-magenta = '#af85ff'
light-cyan = '#1dbfcf'
light-white = '#857f8f'
