[colors]
background = '#232025'
foreground = '#efd5c5'
selection-background = '#544a50'
selection-foreground = '#efd5c5'
cursor = '#f3c09a'
black = '#322f34'
red = '#ff6f6f'
green = '#51b04f'
yellow = '#c0b24f'
blue = '#57b0ff'
magenta = '#ffaacf'
cyan = '#6fb3c0'
white = '#efd5c5'
dim-black = '#322f34'
dim-red = '#f3a0a0'
dim-green = '#a9c99f'
dim-yellow = '#caa89f'
dim-blue = '#a0a0cf'
dim-magenta = '#e3b0c0'
dim-cyan = '#99bfcf'
dim-white = '#8f8886'
light-black = '#5b595e'
light-red = '#e47980'
light-green = '#3fc489'
light-yellow = '#deb07a'
light-blue = '#12b4ff'
light-magenta = '#d0b0ff'
light-cyan = '#65c5a8'
light-white = '#8f8886'
