[colors]
background = '#f5f5ff'
foreground = '#1a1a2f'
selection-background = '#dadadf'
selection-foreground = '#1a1a2f'
cursor = '#0000bb'
black = '#e8e8ea'
red = '#d3303a'
green = '#217a3c'
yellow = '#805d00'
blue = '#375cd8'
magenta = '#ba35af'
cyan = '#1f6fbf'
white = '#1a1a2f'
dim-black = '#e8e8ea'
dim-red = '#c24552'
dim-green = '#61756c'
dim-yellow = '#776d6a'
dim-blue = '#6060d0'
dim-magenta = '#9f5080'
dim-cyan = '#506fa0'
dim-white = '#70627f'
light-black = '#b3b3c0'
light-red = '#d50f7f'
light-green = '#008058'
light-yellow = '#765040'
light-blue = '#065fff'
light-magenta = '#6052cf'
light-cyan = '#1f77bb'
light-white = '#70627f'
