[colors]
background = '#fff8f0'
foreground = '#222222'
selection-background = '#caeafa'
selection-foreground = '#222222'
cursor = '#1144ff'
black = '#f6ece8'
red = '#cc3333'
green = '#217a3c'
yellow = '#8a5d00'
blue = '#375cd8'
magenta = '#ba35af'
cyan = '#1f6fbf'
white = '#222222'
dim-black = '#f6ece8'
dim-red = '#a2403f'
dim-green = '#61756c'
dim-yellow = '#765640'
dim-blue = '#6060d0'
dim-magenta = '#af569f'
dim-cyan = '#406f90'
dim-white = '#63728f'
light-black = '#c7c0ba'
light-red = '#c04440'
light-green = '#008058'
light-yellow = '#8f5a3a'
light-blue = '#065fff'
light-magenta = '#6052cf'
light-cyan = '#1f77bb'
light-white = '#63728f'
