[colors]
background = '#000a1f'
foreground = '#ddddee'
selection-background = '#223848'
selection-foreground = '#ddddee'
cursor = '#ffff00'
black = '#121f34'
red = '#cf8560'
green = '#3faa26'
yellow = '#aa9f32'
blue = '#3f90f0'
magenta = '#b379bf'
cyan = '#5faaef'
white = '#ddddee'
dim-black = '#121f34'
dim-red = '#b57f82'
dim-green = '#61a06c'
dim-yellow = '#af9a6a'
dim-blue = '#7a94df'
dim-magenta = '#c59fcf'
dim-cyan = '#8aa0df'
dim-white = '#7f8797'
light-black = '#445165'
light-red = '#cf7a7a'
light-green = '#3fa672'
light-yellow = '#bfaf7a'
light-blue = '#009fff'
light-magenta = '#9f95ff'
light-cyan = '#0db0ff'
light-white = '#7f8797'
