[colors]
background = '#070019'
foreground = '#d0d0d0'
selection-background = '#042a50'
selection-foreground = '#d0d0d0'
cursor = '#ef6f11'
black = '#1d1a26'
red = '#ef656a'
green = '#1fa526'
yellow = '#c48702'
blue = '#379cf6'
magenta = '#d369af'
cyan = '#5faaef'
white = '#d0d0d0'
dim-black = '#1d1a26'
dim-red = '#d08f72'
dim-green = '#61a06c'
dim-yellow = '#9f8f6a'
dim-blue = '#8a9fdf'
dim-magenta = '#c57faf'
dim-cyan = '#8aa0df'
dim-white = '#857f8f'
light-black = '#4a4759'
light-red = '#ef798f'
light-green = '#00b982'
light-yellow = '#df805f'
light-blue = '#029fff'
light-magenta = '#af85ff'
light-cyan = '#0dafdf'
light-white = '#857f8f'
