[colors]
background = '#f1ecd0'
foreground = '#231a1f'
selection-background = '#ddc5af'
selection-foreground = '#231a1f'
cursor = '#774400'
black = '#e4dbc0'
red = '#882000'
green = '#226022'
yellow = '#6b4500'
blue = '#113384'
magenta = '#822478'
cyan = '#125a7f'
white = '#231a1f'
dim-black = '#e4dbc0'
dim-red = '#702f1f'
dim-green = '#42573f'
dim-yellow = '#6a5937'
dim-blue = '#2f3460'
dim-magenta = '#603a6f'
dim-cyan = '#304f60'
dim-white = '#685f53'
light-black = '#aea88e'
light-red = '#8f0038'
light-green = '#006e50'
light-yellow = '#775228'
light-blue = '#000080'
light-magenta = '#50119f'
light-cyan = '#00676f'
light-white = '#685f53'
