[colors]
background = '#edf5e2'
foreground = '#221321'
selection-background = '#d9d2ef'
selection-foreground = '#221321'
cursor = '#770080'
black = '#e3e9d6'
red = '#c3303a'
green = '#00601f'
yellow = '#9a501f'
blue = '#375cc6'
magenta = '#80308f'
cyan = '#1f70af'
white = '#221321'
dim-black = '#e3e9d6'
dim-red = '#894852'
dim-green = '#306630'
dim-yellow = '#7f4f4a'
dim-blue = '#3a5099'
dim-magenta = '#6a4a9f'
dim-cyan = '#4f677f'
dim-white = '#676470'
light-black = '#b0b7aa'
light-red = '#b02440'
light-green = '#007047'
light-yellow = '#88541f'
light-blue = '#162f8f'
light-magenta = '#5032aa'
light-cyan = '#00677f'
light-white = '#676470'
