[colors]
background = '#222524'
foreground = '#eaf2ef'
selection-background = '#543040'
selection-foreground = '#eaf2ef'
cursor = '#ef7fa8'
black = '#303332'
red = '#ff656a'
green = '#7fc87f'
yellow = '#cac85f'
blue = '#57aff6'
magenta = '#f59acf'
cyan = '#6fcfd2'
white = '#eaf2ef'
dim-black = '#303332'
dim-red = '#eba8a8'
dim-green = '#a9c99f'
dim-yellow = '#cac89f'
dim-blue = '#6ab4ef'
dim-magenta = '#d0b9f0'
dim-cyan = '#99bfcf'
dim-white = '#969faf'
light-black = '#5e6160'
light-red = '#fa7f88'
light-green = '#50cf89'
light-yellow = '#cfb27f'
light-blue = '#62cfef'
light-magenta = '#cfaaff'
light-cyan = '#60d5c2'
light-white = '#969faf'
