[colors]
background = '#fcffff'
foreground = '#232323'
selection-background = '#d4eaf3'
selection-foreground = '#232323'
cursor = '#0055bb'
black = '#eaefef'
red = '#c42d2f'
green = '#008a00'
yellow = '#aa6100'
blue = '#004fc0'
magenta = '#aa44c5'
cyan = '#1f6fbf'
white = '#232323'
dim-black = '#eaefef'
dim-red = '#9a4366'
dim-green = '#517f3c'
dim-yellow = '#7a5f2f'
dim-blue = '#375cc8'
dim-magenta = '#605f9f'
dim-cyan = '#305f9f'
dim-white = '#66657f'
light-black = '#b5b8b8'
light-red = '#cf2f4f'
light-green = '#00845f'
light-yellow = '#996c4f'
light-blue = '#065fff'
light-magenta = '#7f5ae0'
light-cyan = '#007a85'
light-white = '#66657f'
