[colors]
background = '#fff7f7'
foreground = '#201f36'
selection-background = '#dfe4f4'
selection-foreground = '#201f36'
cursor = '#d06f30'
black = '#efe7e7'
red = '#b00234'
green = '#217a3c'
yellow = '#9a6012'
blue = '#3c3bbe'
magenta = '#a01f64'
cyan = '#2f5f9f'
white = '#201f36'
dim-black = '#efe7e7'
dim-red = '#af3f5f'
dim-green = '#61756c'
dim-yellow = '#a65d6a'
dim-blue = '#6060d0'
dim-magenta = '#954f90'
dim-cyan = '#506fa0'
dim-white = '#776f79'
light-black = '#c0bbbb'
light-red = '#d5305f'
light-green = '#008358'
light-yellow = '#a04646'
light-blue = '#065fff'
light-magenta = '#7022bf'
light-cyan = '#1077ab'
light-white = '#776f79'
