[colors]
background = '#ffffff'
foreground = '#202020'
selection-background = '#bfefff'
selection-foreground = '#202020'
cursor = '#0033cc'
black = '#efefef'
red = '#d3303a'
green = '#217a3c'
yellow = '#a45f22'
blue = '#3740cf'
magenta = '#ba35af'
cyan = '#1f6fbf'
white = '#202020'
dim-black = '#efefef'
dim-red = '#c24552'
dim-green = '#61756c'
dim-yellow = '#a65f6a'
dim-blue = '#4f54ba'
dim-magenta = '#af5a80'
dim-cyan = '#506fa0'
dim-white = '#70627f'
light-black = '#b3b3b3'
light-red = '#d50f7f'
light-green = '#008858'
light-yellow = '#b65050'
light-blue = '#065fff'
light-magenta = '#6052cf'
light-cyan = '#1f77bb'
light-white = '#70627f'
