[colors]
background = '#352718'
foreground = '#e8e4b1'
selection-background = '#443a4f'
selection-foreground = '#e8e4b1'
cursor = '#f9cf7a'
black = '#483426'
red = '#ff7f7f'
green = '#6fd560'
yellow = '#e4b53f'
blue = '#57aff6'
magenta = '#f0aac5'
cyan = '#6fcad0'
white = '#e8e4b1'
dim-black = '#483426'
dim-red = '#e89a88'
dim-green = '#a0d26f'
dim-yellow = '#eab780'
dim-blue = '#6ab4ef'
dim-magenta = '#dfcfe0'
dim-cyan = '#99bfcf'
dim-white = '#90918a'
light-black = '#79665f'
light-red = '#ff8f98'
light-green = '#65d590'
light-yellow = '#e7a06f'
light-blue = '#62cfef'
light-magenta = '#c6a2fe'
light-cyan = '#70e0cf'
light-white = '#90918a'
