[colors]
background = '#fff6d8'
foreground = '#484431'
selection-background = '#f0d4d8'
selection-foreground = '#484431'
cursor = '#a07f00'
black = '#f5e9cb'
red = '#ba2d2f'
green = '#007a0a'
yellow = '#a26310'
blue = '#375cc6'
magenta = '#aa3e74'
cyan = '#3f60af'
white = '#484431'
dim-black = '#f5e9cb'
dim-red = '#b05350'
dim-green = '#61756c'
dim-yellow = '#7f6f1a'
dim-blue = '#4a659f'
dim-magenta = '#905ea0'
dim-cyan = '#4f6f8f'
dim-white = '#68708a'
light-black = '#c7b7a6'
light-red = '#c02945'
light-green = '#008250'
light-yellow = '#946830'
light-blue = '#265fbf'
light-magenta = '#6448ca'
light-cyan = '#0f708a'
light-white = '#68708a'
