[colors]
background = '#edf4f8'
foreground = '#151a27'
selection-background = '#c8dcff'
selection-foreground = '#151a27'
cursor = '#036f99'
black = '#e0e7ef'
red = '#c3303a'
green = '#007010'
yellow = '#805a1f'
blue = '#375cc6'
magenta = '#80308f'
cyan = '#1f66af'
white = '#151a27'
dim-black = '#e0e7ef'
dim-red = '#8b4052'
dim-green = '#4a763f'
dim-yellow = '#7f4f4a'
dim-blue = '#3a5099'
dim-magenta = '#6a4a9f'
dim-cyan = '#3f627f'
dim-white = '#676470'
light-black = '#afb8c3'
light-red = '#b02440'
light-green = '#007047'
light-yellow = '#78542f'
light-blue = '#003faf'
light-magenta = '#5f2fba'
light-cyan = '#006f70'
light-white = '#676470'
