[colors]
background = '#131c2b'
foreground = '#eaedef'
selection-background = '#183c65'
selection-foreground = '#eaedef'
cursor = '#8fdfff'
black = '#1d2c39'
red = '#ff6f6f'
green = '#41bf4f'
yellow = '#d0d24f'
blue = '#57b0ff'
magenta = '#f59acf'
cyan = '#2fd0db'
white = '#eaedef'
dim-black = '#1d2c39'
dim-red = '#eaa4a4'
dim-green = '#a9c99f'
dim-yellow = '#cac89f'
dim-blue = '#9acfff'
dim-magenta = '#d4aaf0'
dim-cyan = '#99bfcf'
dim-white = '#969faf'
light-black = '#4a5664'
light-red = '#ff7788'
light-green = '#30c489'
light-yellow = '#cab27f'
light-blue = '#12b4ff'
light-magenta = '#cf90ff'
light-cyan = '#65d5a8'
light-white = '#969faf'
