[colors]
background = '#000e17'
foreground = '#afbcbf'
selection-background = '#253146'
selection-foreground = '#afbcbf'
cursor = '#00ccff'
black = '#1a202b'
red = '#ef656a'
green = '#1fa526'
yellow = '#c48502'
blue = '#379cf6'
magenta = '#d570af'
cyan = '#4fb0cf'
white = '#afbcbf'
dim-black = '#1a202b'
dim-red = '#d56f72'
dim-green = '#61a06c'
dim-yellow = '#cf9f7f'
dim-blue = '#7a94df'
dim-magenta = '#c59faf'
dim-cyan = '#92b4df'
dim-white = '#70819f'
light-black = '#444e59'
light-red = '#ef798f'
light-green = '#00a972'
light-yellow = '#df8f6f'
light-blue = '#029fff'
light-magenta = '#af8aff'
light-cyan = '#3dc0b0'
light-white = '#70819f'
