[colors]
background = '#292c2f'
foreground = '#d0d0d0'
selection-background = '#404f66'
selection-foreground = '#d0d0d0'
cursor = '#afe6ef'
black = '#373b3d'
red = '#d67869'
green = '#70bb70'
yellow = '#c09f6f'
blue = '#80a4e0'
magenta = '#e5a0ea'
cyan = '#8fb8ea'
white = '#d0d0d0'
dim-black = '#373b3d'
dim-red = '#eba0af'
dim-green = '#9fb3a7'
dim-yellow = '#cbb0a0'
dim-blue = '#aab2df'
dim-magenta = '#e5bbd7'
dim-cyan = '#a2c5d8'
dim-white = '#857f8f'
light-black = '#60676b'
light-red = '#e4959f'
light-green = '#60bd90'
light-yellow = '#cf9f90'
light-blue = '#72aff0'
light-magenta = '#cfa0e8'
light-cyan = '#7ac0b9'
light-white = '#857f8f'
