[colors]
background = '#322023'
foreground = '#e4d3e1'
selection-background = '#45524a'
selection-foreground = '#e4d3e1'
cursor = '#ef607a'
black = '#432e32'
red = '#ff707f'
green = '#5fbb5f'
yellow = '#e4c53f'
blue = '#57aff6'
magenta = '#ffb2d6'
cyan = '#5fc0dc'
white = '#e4d3e1'
dim-black = '#432e32'
dim-red = '#e89f84'
dim-green = '#9aba8b'
dim-yellow = '#d8c09f'
dim-blue = '#9fbfdf'
dim-magenta = '#c59fdf'
dim-cyan = '#99bfcf'
dim-white = '#9d9d9d'
light-black = '#6a5862'
light-red = '#f0888f'
light-green = '#49d081'
light-yellow = '#eec26f'
light-blue = '#62cff7'
light-magenta = '#cfb1ff'
light-cyan = '#80dfbf'
light-white = '#9d9d9d'
