[colors]
background = '#f3eddf'
foreground = '#4f204f'
selection-background = '#e0d0ba'
selection-foreground = '#4f204f'
cursor = '#9d5744'
black = '#e5d6d4'
red = '#ba2d2f'
green = '#007a0a'
yellow = '#87591f'
blue = '#375cc6'
magenta = '#9f4e74'
cyan = '#3060af'
white = '#4f204f'
dim-black = '#e5d6d4'
dim-red = '#a04650'
dim-green = '#426340'
dim-yellow = '#7a5c50'
dim-blue = '#475d8e'
dim-magenta = '#97508f'
dim-cyan = '#456b82'
dim-white = '#6f6877'
light-black = '#b9aaa8'
light-red = '#a83058'
light-green = '#008250'
light-yellow = '#906045'
light-blue = '#265fbf'
light-magenta = '#7755b4'
light-cyan = '#0b6e8a'
light-white = '#6f6877'
