[colors]
background = '#fff2f3'
foreground = '#4f4073'
selection-background = '#eecfff'
selection-foreground = '#4f4073'
cursor = '#cf0090'
black = '#f2e4ea'
red = '#d3303a'
green = '#217a3c'
yellow = '#a45f22'
blue = '#375ce6'
magenta = '#ba35af'
cyan = '#1f6fbf'
white = '#4f4073'
dim-black = '#f2e4ea'
dim-red = '#c24552'
dim-green = '#61756c'
dim-yellow = '#9a5f6a'
dim-blue = '#6060d0'
dim-magenta = '#a45392'
dim-cyan = '#5f60bf'
dim-white = '#786e74'
light-black = '#cfb3c4'
light-red = '#d50f7f'
light-green = '#007f68'
light-yellow = '#b65050'
light-blue = '#065fff'
light-magenta = '#8e44f3'
light-cyan = '#0f7b8f'
light-white = '#786e74'
