[colors]
background = '#f6fff9'
foreground = '#34494a'
selection-background = '#d0e6ff'
selection-foreground = '#34494a'
cursor = '#bf005f'
black = '#e8f0f0'
red = '#c42d2f'
green = '#1a870f'
yellow = '#a45f22'
blue = '#375cc6'
magenta = '#d5206f'
cyan = '#1f6fbf'
white = '#34494a'
dim-black = '#e8f0f0'
dim-red = '#b64850'
dim-green = '#61756c'
dim-yellow = '#876450'
dim-blue = '#6a65bf'
dim-magenta = '#a04360'
dim-cyan = '#5f6abf'
dim-white = '#777294'
light-black = '#c0c6c3'
light-red = '#cf2f4f'
light-green = '#007f68'
light-yellow = '#ae5a30'
light-blue = '#265fbf'
light-magenta = '#9435b4'
light-cyan = '#0f7b8f'
light-white = '#777294'
