[colors]
background = '#130911'
foreground = '#d0d0d0'
selection-background = '#3f2f40'
selection-foreground = '#d0d0d0'
cursor = '#f0af7f'
black = '#221920'
red = '#ef6360'
green = '#0faa26'
yellow = '#bf9032'
blue = '#3f95f6'
magenta = '#d369af'
cyan = '#4fbaef'
white = '#d0d0d0'
dim-black = '#221920'
dim-red = '#d56f72'
dim-green = '#61a06c'
dim-yellow = '#cf9f8f'
dim-blue = '#7a94df'
dim-magenta = '#c58faf'
dim-cyan = '#8aa0df'
dim-white = '#857f8f'
light-black = '#4b3f47'
light-red = '#fe5a7a'
light-green = '#00a692'
light-yellow = '#df8a5a'
light-blue = '#029fff'
light-magenta = '#af85ff'
light-cyan = '#1dbfcf'
light-white = '#857f8f'
