[colors]
background = '#fff9f9'
foreground = '#1a1a1a'
selection-background = '#dadadf'
selection-foreground = '#1a1a1a'
cursor = '#bb0000'
black = '#efecec'
red = '#aa0010'
green = '#217a3c'
yellow = '#805d00'
blue = '#375cd8'
magenta = '#aa357f'
cyan = '#2070af'
white = '#1a1a1a'
dim-black = '#efecec'
dim-red = '#92454f'
dim-green = '#61756c'
dim-yellow = '#776d6a'
dim-blue = '#6060d0'
dim-magenta = '#7f4580'
dim-cyan = '#5f6a90'
dim-white = '#756275'
light-black = '#bdb9b9'
light-red = '#c50f4f'
light-green = '#008058'
light-yellow = '#765040'
light-blue = '#065fff'
light-magenta = '#af40af'
light-cyan = '#007faa'
light-white = '#756275'
