[colors]
background = '#160f0f'
foreground = '#d8cfd5'
selection-background = '#16304f'
selection-foreground = '#d8cfd5'
cursor = '#ff99ff'
black = '#2a2228'
red = '#f48359'
green = '#60b444'
yellow = '#d4a052'
blue = '#7fa5f6'
magenta = '#d37faf'
cyan = '#8fbaff'
white = '#d8cfd5'
dim-black = '#2a2228'
dim-red = '#e07a9a'
dim-green = '#61a06c'
dim-yellow = '#c7a07f'
dim-blue = '#7a94df'
dim-magenta = '#c9addf'
dim-cyan = '#8ac0ef'
dim-white = '#908890'
light-black = '#564f55'
light-red = '#ff85aa'
light-green = '#60bf88'
light-yellow = '#ef9680'
light-blue = '#72afff'
light-magenta = '#a698ef'
light-cyan = '#8fcfdf'
light-white = '#908890'
