[colors]
background = '#15050f'
foreground = '#dfd0d5'
selection-background = '#293140'
selection-foreground = '#dfd0d5'
cursor = '#fd3333'
black = '#282026'
red = '#cf4f5f'
green = '#2fa526'
yellow = '#c48702'
blue = '#379cf6'
magenta = '#b0648f'
cyan = '#3fafcf'
white = '#dfd0d5'
dim-black = '#282026'
dim-red = '#b07f7f'
dim-green = '#5f9f6f'
dim-yellow = '#cf9f7f'
dim-blue = '#6a84af'
dim-magenta = '#c590af'
dim-cyan = '#82a0af'
dim-white = '#908890'
light-black = '#554f4f'
light-red = '#d24f7f'
light-green = '#00b066'
light-yellow = '#df8f6f'
light-blue = '#029fff'
light-magenta = '#a6699f'
light-cyan = '#4fafaf'
light-white = '#908890'
