[colors]
background = '#f8f5ff'
foreground = '#4f3363'
selection-background = '#eed0ff'
selection-foreground = '#4f3363'
cursor = '#4f45ff'
black = '#ebe7f1'
red = '#c3303a'
green = '#057800'
yellow = '#a45f22'
blue = '#375cd6'
magenta = '#ad45ba'
cyan = '#1f6fbf'
white = '#4f3363'
dim-black = '#ebe7f1'
dim-red = '#a24568'
dim-green = '#41754c'
dim-yellow = '#a05b5f'
dim-blue = '#6060d0'
dim-magenta = '#804fb0'
dim-cyan = '#5f60bf'
dim-white = '#786e74'
light-black = '#c3c0c9'
light-red = '#c01f5f'
light-green = '#007f6f'
light-yellow = '#b65050'
light-blue = '#065fbf'
light-magenta = '#705ae3'
light-cyan = '#0f7a9d'
light-white = '#786e74'
