[colors]
background = '#000000'
foreground = '#ffffff'
selection-background = '#5a5a5a'
selection-foreground = '#ffffff'
cursor = '#ffffff'
black = '#1e1e1e'
red = '#ff5f59'
green = '#44bc44'
yellow = '#cabf00'
blue = '#2fafff'
magenta = '#feacd0'
cyan = '#00d3d0'
white = '#ffffff'
dim-black = '#1e1e1e'
dim-red = '#ff9070'
dim-green = '#88ca9f'
dim-yellow = '#d2b580'
dim-blue = '#82b0ec'
dim-magenta = '#caa6df'
dim-cyan = '#7fdbdf'
dim-white = '#989898'
light-black = '#535353'
light-red = '#ff6f9f'
light-green = '#00c06f'
light-yellow = '#d8af7a'
light-blue = '#00bcff'
light-magenta = '#b6a0ff'
light-cyan = '#6ae4b9'
light-white = '#989898'
