[colors]
background = '#ffffff'
foreground = '#000000'
selection-background = '#bdbdbd'
selection-foreground = '#000000'
cursor = 'blue_intense'
black = '#f2f2f2'
red = '#a60000'
green = '#006800'
yellow = '#695500'
blue = '#0031a9'
magenta = '#721045'
cyan = '#005e8b'
white = '#000000'
dim-black = '#f2f2f2'
dim-red = '#7f0000'
dim-green = '#2a5045'
dim-yellow = '#624416'
dim-blue = '#003497'
dim-magenta = '#7c318f'
dim-cyan = '#005077'
dim-white = '#595959'
light-black = '#c4c4c4'
light-red = '#a0132f'
light-green = '#00663f'
light-yellow = '#77492f'
light-blue = '#0000b0'
light-magenta = '#531ab6'
light-cyan = '#005f5f'
light-white = '#595959'
