[colors]
background = '#0d0e1c'
foreground = '#ffffff'
selection-background = '#555a66'
selection-foreground = '#ffffff'
cursor = 'magenta_warmer'
black = '#1d2235'
red = '#ff5f59'
green = '#44bc44'
yellow = '#d0bc00'
blue = '#2fafff'
magenta = '#feacd0'
cyan = '#00d3d0'
white = '#ffffff'
dim-black = '#1d2235'
dim-red = '#ff9f80'
dim-green = '#88ca9f'
dim-yellow = '#d2b580'
dim-blue = '#82b0ec'
dim-magenta = '#caa6df'
dim-cyan = '#9ac8e0'
dim-white = '#989898'
light-black = '#4a4f69'
light-red = '#ff7f9f'
light-green = '#00c06f'
light-yellow = '#dfaf7a'
light-blue = '#00bcff'
light-magenta = '#b6a0ff'
light-cyan = '#6ae4b9'
light-white = '#989898'
